---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 1h
  releaseName: rook-ceph-cluster
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
      version: 1.13.5
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    cephClusterSpec:
      dashboard:
        ssl: false
      storage:
        useAllNodes: true
        useAllDevices: true
        deviceFilter: "^sd[c-d]"
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-http01"
        host:
          name: "ceph.${domain}"
        tls:
          - hosts:
            - "ceph.${domain}"
    cephObjectStores:
      - name: objectstore
        # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              limits:
                cpu: "2000m"
                memory: "2Gi"
              requests:
                cpu: "1000m"
                memory: "1Gi"
            # securePort: 443
            # sslCertificateRef:
            instances: 1
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          volumeBindingMode: "Immediate"
          # see https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#storageclass for available configuration
          parameters: {}
            # note: objectStoreNamespace and objectStoreName are configured by the chart
        ingress:
          # Enable an ingress for the ceph-objectstore
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-http01"
          host:
            name: "s3.${domain}"
            path: /
          tls:
          - hosts:
              - "s3.${domain}"
          #   secretName: ceph-objectstore-tls
