---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/apps
  # dependsOn:
  #   - name: configs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: rfc2136dnsserver
